export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const TODOS_LOADING = 'TODOS_LOADING';
export const ADD_TODOS = 'ADD_TODOS';
export const TODOS_FAILED = 'TODOS_FAILED';